# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kxfed_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(539, 759)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(459, 629))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.team_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_label.sizePolicy().hasHeightForWidth())
        self.team_label.setSizePolicy(sizePolicy)
        self.team_label.setObjectName("team_label")
        self.horizontalLayout_2.addWidget(self.team_label)
        self.team_combo = QtWidgets.QComboBox(self.centralwidget)
        self.team_combo.setEnabled(False)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_combo.sizePolicy().hasHeightForWidth())
        self.team_combo.setSizePolicy(sizePolicy)
        self.team_combo.setEditable(False)
        self.team_combo.setObjectName("team_combo")
        self.horizontalLayout_2.addWidget(self.team_combo)
        self.horizontalLayout_2.setStretch(0, 1)

        self.horizontalLayout_2.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ppa_label = QtWidgets.QLabel(self.centralwidget)
        self.ppa_label.setObjectName("ppa_label")
        self.horizontalLayout_3.addWidget(self.ppa_label)
        self.ppa_combo = QtWidgets.QComboBox(self.centralwidget)
        self.ppa_combo.setEnabled(True)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppa_combo.sizePolicy().hasHeightForWidth())
        self.ppa_combo.setSizePolicy(sizePolicy)
        self.ppa_combo.setObjectName("ppa_combo")
        self.horizontalLayout_3.addWidget(self.ppa_combo)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.arch_label = QtWidgets.QLabel(self.centralwidget)
        self.arch_label.setObjectName("arch_label")
        self.horizontalLayout.addWidget(self.arch_label)
        self.arch_combo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arch_combo.sizePolicy().hasHeightForWidth())
        self.arch_combo.setSizePolicy(sizePolicy)
        self.arch_combo.setObjectName("arch_combo")
        self.horizontalLayout.addWidget(self.arch_combo)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.packages_label = QtWidgets.QLabel(self.centralwidget)
        self.packages_label.setObjectName("packages_label")
        self.verticalLayout.addWidget(self.packages_label)
        self.pkgs_tableView = QtWidgets.QTableView(self.centralwidget)
        self.pkgs_tableView.setObjectName("pkgs_tableView")
        self.verticalLayout.addWidget(self.pkgs_tableView)
        self.kernelbuild_chk = QtWidgets.QCheckBox(self.centralwidget)
        self.kernelbuild_chk.setObjectName("kernelbuild_chk")
        self.verticalLayout.addWidget(self.kernelbuild_chk)
        self.lowlatency_chk = QtWidgets.QCheckBox(self.centralwidget)
        self.lowlatency_chk.setObjectName("lowlatency_chk")
        self.verticalLayout.addWidget(self.lowlatency_chk)
        self.reconnectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.reconnectBtn.setMinimumSize(QtCore.QSize(88, 27))
        self.reconnectBtn.setMaximumSize(QtCore.QSize(88, 27))
        self.reconnectBtn.setObjectName("reconnectBtn")
        self.verticalLayout.addWidget(self.reconnectBtn)
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setEnabled(True)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.transaction_progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.transaction_progress_bar.setProperty("value", 24)
        self.transaction_progress_bar.setObjectName("transaction_progress_bar")
        self.verticalLayout.addWidget(self.transaction_progress_bar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.install_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.install_btn.sizePolicy().hasHeightForWidth())
        self.install_btn.setSizePolicy(sizePolicy)
        self.install_btn.setObjectName("install_btn")
        self.horizontalLayout_4.addWidget(self.install_btn)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 5)
        self.verticalLayout.setStretch(3, 5)
        self.verticalLayout.setStretch(4, 35)
        self.verticalLayout.setStretch(5, 5)
        self.verticalLayout.setStretch(6, 5)
        self.verticalLayout.setStretch(7, 5)
        self.verticalLayout.setStretch(8, 5)
        self.verticalLayout.setStretch(10, 7)
        self.gridLayout.addLayout(self.verticalLayout, 14, 0, 1, 1)
        self.load_label = QtWidgets.QLabel(self.centralwidget)
        self.load_label.setGeometry(QtCore.QRect(162, 260, 145, 28))
        self.load_label.setObjectName("load_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setMinimumSize(QtCore.QSize(0, 0))
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 539, 27))
        self.menuBar.setObjectName("menuBar")
        self.menuPreferences = QtWidgets.QMenu(self.menuBar)
        self.menuPreferences.setObjectName("menuPreferences")
        MainWindow.setMenuBar(self.menuBar)
        self.btn_edit_config = QtWidgets.QAction(MainWindow)
        self.btn_edit_config.setObjectName("btn_edit_config")
        self.btn_quit = QtWidgets.QAction(MainWindow)
        self.btn_quit.setObjectName("btn_quit")
        self.btn_refresh_cache = QtWidgets.QAction(MainWindow)
        self.btn_refresh_cache.setObjectName("btn_refresh_cache")
        self.btn_show_messages = QtWidgets.QAction(MainWindow)
        self.btn_show_messages.setObjectName("btn_show_messages")
        self.menuPreferences.addAction(self.btn_refresh_cache)
        self.menuPreferences.addAction(self.btn_show_messages)
        self.menuPreferences.addAction(self.btn_edit_config)
        self.menuPreferences.addSeparator()
        self.menuPreferences.addAction(self.btn_quit)
        self.menuBar.addAction(self.menuPreferences.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KXFed - KXStudio on Fedora"))
        self.lowlatency_chk.setText(_translate("MainWindow", "Lowlatency"))
        self.reconnectBtn.setText(_translate("MainWindow", "Reconnect"))
        self.team_label.setText(_translate("MainWindow", "Team :"))
        self.ppa_label.setText(_translate("MainWindow", "PPA : "))
        self.arch_label.setText(_translate("MainWindow", "Arch : "))
        self.packages_label.setText(_translate("MainWindow", "Packages: "))
        self.arch_label.setText(_translate("MainWindow", "Arch :"))
        self.kernelbuild_chk.setText(_translate("MainWindow", "Build and install latest RT kernel"))
        self.lowlatency_chk.setText(_translate("MainWindow", "Lowlatency"))
        self.reconnectBtn.setText(_translate("MainWindow", "Reconnect"))
        self.install_btn.setText(_translate("MainWindow", "Process Pkgs"))
        self.load_label.setText(_translate("MainWindow", "TextLabel"))
        self.menuPreferences.setTitle(_translate("MainWindow", "&Preferences..."))
        self.btn_edit_config.setText(_translate("MainWindow", "&Edit Configuration"))
        self.btn_quit.setText(_translate("MainWindow", "Exit"))
        self.btn_refresh_cache.setText(_translate("MainWindow", "&Refresh Cache"))
        self.btn_show_messages.setText(_translate("MainWindow", "&Messages"))


