# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/lprpm_prefs_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from ui.qlabelchanged import QLabelChanged


class UiLPRpmPrefsDialog(object):
    def setupUi(self, prefs_dialog):
        prefs_dialog.setObjectName("prefs_dialog")
        prefs_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        prefs_dialog.resize(290, 424)
        self.gridLayout = QtWidgets.QGridLayout(prefs_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.download_chkbox = QtWidgets.QCheckBox(prefs_dialog)
        self.download_chkbox.setChecked(True)
        self.download_chkbox.setObjectName("download_chkbox")
        self.verticalLayout_1.addWidget(self.download_chkbox)
        self.convert_chkbox = QtWidgets.QCheckBox(prefs_dialog)
        self.convert_chkbox.setChecked(True)
        self.convert_chkbox.setObjectName("convert_chkbox")
        self.verticalLayout_1.addWidget(self.convert_chkbox)
        self.install_chkbox = QtWidgets.QCheckBox(prefs_dialog)
        self.install_chkbox.setChecked(True)
        self.install_chkbox.setObjectName("install_chkbox")
        self.verticalLayout_1.addWidget(self.install_chkbox)
        self.uninstall_chkbox = QtWidgets.QCheckBox(prefs_dialog)
        self.uninstall_chkbox.setChecked(True)
        self.uninstall_chkbox.setObjectName("uninstall_chkbox")
        self.verticalLayout_1.addWidget(self.uninstall_chkbox)
        self.verticalLayout.addLayout(self.verticalLayout_1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.delete_downloaded_chkbox = QtWidgets.QCheckBox(prefs_dialog)
        self.delete_downloaded_chkbox.setChecked(True)
        self.delete_downloaded_chkbox.setObjectName("delete_downloaded_chkbox")
        self.verticalLayout_2.addWidget(self.delete_downloaded_chkbox)
        self.delete_converted_chkbox = QtWidgets.QCheckBox(prefs_dialog)
        self.delete_converted_chkbox.setChecked(True)
        self.delete_converted_chkbox.setObjectName("delete_converted_chkbox")
        self.verticalLayout_2.addWidget(self.delete_converted_chkbox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_3 = QtWidgets.QFrame(prefs_dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(prefs_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.directory_label = QLabelChanged(prefs_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directory_label.sizePolicy().hasHeightForWidth())
        self.directory_label.setSizePolicy(sizePolicy)
        self.directory_label.setToolTip("")
        self.directory_label.setToolTipDuration(3)
        self.directory_label.setStatusTip("")
        self.directory_label.setWhatsThis("")
        self.directory_label.setAutoFillBackground(True)
        self.directory_label.setFrameShape(QtWidgets.QFrame.Box)
        self.directory_label.setObjectName("directory_label")
        self.horizontalLayout_4.addWidget(self.directory_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line = QtWidgets.QFrame(prefs_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(prefs_dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.renew_every_day_chkbox = QtWidgets.QCheckBox(prefs_dialog)
        self.renew_every_day_chkbox.setObjectName("renew_every_day_chkbox")
        self.horizontalLayout_3.addWidget(self.renew_every_day_chkbox)
        self.renew_every_month_chkbox = QtWidgets.QCheckBox(prefs_dialog)
        self.renew_every_month_chkbox.setObjectName("renew_every_month_chkbox")
        self.horizontalLayout_3.addWidget(self.renew_every_month_chkbox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.renew_every_6_months_chkbox = QtWidgets.QCheckBox(prefs_dialog)
        self.renew_every_6_months_chkbox.setObjectName("renew_every_6_months_chkbox")
        self.horizontalLayout_2.addWidget(self.renew_every_6_months_chkbox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.renew_every_time_chkbox = QtWidgets.QCheckBox(prefs_dialog)
        self.renew_every_time_chkbox.setObjectName("renew_every_time_chkbox")
        self.horizontalLayout.addWidget(self.renew_every_time_chkbox)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(prefs_dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.closeButton = QtWidgets.QPushButton(prefs_dialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_5.addWidget(self.closeButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(prefs_dialog)
        QtCore.QMetaObject.connectSlotsByName(prefs_dialog)

    def retranslateUi(self, prefs_dialog):
        _translate = QtCore.QCoreApplication.translate
        prefs_dialog.setWindowTitle(_translate("prefs_dialog", "KXFed Preferences"))
        self.download_chkbox.setText(_translate("prefs_dialog", "Download Checked Packages"))
        self.convert_chkbox.setText(_translate("prefs_dialog", "Convert Checked Packages"))
        self.install_chkbox.setText(_translate("prefs_dialog", "Install Checked Packages"))
        self.uninstall_chkbox.setText(_translate("prefs_dialog", "Uninstall Checked Packages"))
        self.delete_downloaded_chkbox.setText(_translate("prefs_dialog", "Delete Downloaded Packages"))
        self.delete_converted_chkbox.setText(_translate("prefs_dialog", "Delete Converted Packages"))
        self.label.setText(_translate("prefs_dialog", "Working Directory"))
        self.directory_label.setText(_translate("prefs_dialog", "TextLabel"))
        self.label_2.setText(_translate("prefs_dialog", "Renew Caches Automatically"))
        self.renew_every_day_chkbox.setText(_translate("prefs_dialog", "every day"))
        self.renew_every_month_chkbox.setText(_translate("prefs_dialog", "every month"))
        self.renew_every_6_months_chkbox.setText(_translate("prefs_dialog", "every 6 months"))
        self.renew_every_time_chkbox.setText(_translate("prefs_dialog", "when opening"))
        self.closeButton.setText(_translate("prefs_dialog", "Close"))
