# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/settings_app.ui'
#
# Created: Tue Jul 11 07:46:45 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsW(object):
    def setupUi(self, SettingsW):
        SettingsW.setObjectName(_fromUtf8("SettingsW"))
        SettingsW.resize(600, 465)
        SettingsW.setMinimumSize(QtCore.QSize(600, 0))
        self.verticalLayout_2 = QtGui.QVBoxLayout(SettingsW)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lw_page = QtGui.QTableWidget(SettingsW)
        self.lw_page.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lw_page.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lw_page.setProperty("showDropIndicator", False)
        self.lw_page.setDragDropOverwriteMode(False)
        self.lw_page.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lw_page.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lw_page.setIconSize(QtCore.QSize(48, 48))
        self.lw_page.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.lw_page.setWordWrap(False)
        self.lw_page.setCornerButtonEnabled(False)
        self.lw_page.setObjectName(_fromUtf8("lw_page"))
        self.lw_page.setColumnCount(1)
        self.lw_page.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.lw_page.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.lw_page.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.lw_page.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.lw_page.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/exec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.lw_page.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/canvas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.lw_page.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/ladish.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.lw_page.setItem(2, 0, item)
        self.lw_page.horizontalHeader().setVisible(False)
        self.lw_page.horizontalHeader().setStretchLastSection(True)
        self.lw_page.verticalHeader().setVisible(False)
        self.lw_page.verticalHeader().setDefaultSectionSize(52)
        self.horizontalLayout_3.addWidget(self.lw_page)
        self.stackedWidget = QtGui.QStackedWidget(SettingsW)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_main = QtGui.QWidget()
        self.page_main.setObjectName(_fromUtf8("page_main"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_main)
        self.verticalLayout_5.setMargin(2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.page_main)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_icon_main = QtGui.QLabel(self.page_main)
        self.label_icon_main.setText(_fromUtf8(""))
        self.label_icon_main.setPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/exec.png")))
        self.label_icon_main.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_icon_main.setObjectName(_fromUtf8("label_icon_main"))
        self.horizontalLayout.addWidget(self.label_icon_main)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.group_main_paths = QtGui.QGroupBox(self.page_main)
        self.group_main_paths.setObjectName(_fromUtf8("group_main_paths"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.group_main_paths)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.group_main_paths)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.le_main_def_folder = QtGui.QLineEdit(self.group_main_paths)
        self.le_main_def_folder.setObjectName(_fromUtf8("le_main_def_folder"))
        self.horizontalLayout_2.addWidget(self.le_main_def_folder)
        self.b_main_def_folder_open = QtGui.QPushButton(self.group_main_paths)
        self.b_main_def_folder_open.setMaximumSize(QtCore.QSize(22, 22))
        self.b_main_def_folder_open.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/16x16/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_main_def_folder_open.setIcon(icon3)
        self.b_main_def_folder_open.setObjectName(_fromUtf8("b_main_def_folder_open"))
        self.horizontalLayout_2.addWidget(self.b_main_def_folder_open)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.group_main_paths)
        self.group_tray = QtGui.QGroupBox(self.page_main)
        self.group_tray.setObjectName(_fromUtf8("group_tray"))
        self.gridLayout_5 = QtGui.QGridLayout(self.group_tray)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cb_tray_close_to = QtGui.QCheckBox(self.group_tray)
        self.cb_tray_close_to.setEnabled(False)
        self.cb_tray_close_to.setObjectName(_fromUtf8("cb_tray_close_to"))
        self.gridLayout_5.addWidget(self.cb_tray_close_to, 1, 0, 1, 1)
        self.cb_tray_enable = QtGui.QCheckBox(self.group_tray)
        self.cb_tray_enable.setObjectName(_fromUtf8("cb_tray_enable"))
        self.gridLayout_5.addWidget(self.cb_tray_enable, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.group_tray)
        self.groupBox_3 = QtGui.QGroupBox(self.page_main)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.sb_gui_refresh = QtGui.QSpinBox(self.groupBox_3)
        self.sb_gui_refresh.setMinimum(10)
        self.sb_gui_refresh.setMaximum(1000)
        self.sb_gui_refresh.setProperty("value", 250)
        self.sb_gui_refresh.setObjectName(_fromUtf8("sb_gui_refresh"))
        self.gridLayout_4.addWidget(self.sb_gui_refresh, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_jack_port_alias = QtGui.QLabel(self.groupBox_3)
        self.label_jack_port_alias.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jack_port_alias.setObjectName(_fromUtf8("label_jack_port_alias"))
        self.gridLayout_4.addWidget(self.label_jack_port_alias, 1, 0, 1, 1)
        self.cb_jack_port_alias = QtGui.QComboBox(self.groupBox_3)
        self.cb_jack_port_alias.setObjectName(_fromUtf8("cb_jack_port_alias"))
        self.cb_jack_port_alias.addItem(_fromUtf8(""))
        self.cb_jack_port_alias.addItem(_fromUtf8(""))
        self.cb_jack_port_alias.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cb_jack_port_alias, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page_main)
        self.page_canvas = QtGui.QWidget()
        self.page_canvas.setObjectName(_fromUtf8("page_canvas"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_canvas)
        self.verticalLayout_8.setMargin(2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.page_canvas)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.label_10 = QtGui.QLabel(self.page_canvas)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/canvas.png")))
        self.label_10.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.groupBox_4 = QtGui.QGroupBox(self.page_canvas)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 4, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 2)
        self.cb_canvas_bezier_lines = QtGui.QCheckBox(self.groupBox_4)
        self.cb_canvas_bezier_lines.setObjectName(_fromUtf8("cb_canvas_bezier_lines"))
        self.gridLayout_2.addWidget(self.cb_canvas_bezier_lines, 1, 2, 1, 3)
        self.cb_canvas_theme = QtGui.QComboBox(self.groupBox_4)
        self.cb_canvas_theme.setObjectName(_fromUtf8("cb_canvas_theme"))
        self.gridLayout_2.addWidget(self.cb_canvas_theme, 0, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_7 = QtGui.QGroupBox(self.page_canvas)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.cb_canvas_hide_groups = QtGui.QCheckBox(self.groupBox_7)
        self.cb_canvas_hide_groups.setObjectName(_fromUtf8("cb_canvas_hide_groups"))
        self.verticalLayout_7.addWidget(self.cb_canvas_hide_groups)
        self.cb_canvas_eyecandy = QtGui.QCheckBox(self.groupBox_7)
        self.cb_canvas_eyecandy.setTristate(True)
        self.cb_canvas_eyecandy.setObjectName(_fromUtf8("cb_canvas_eyecandy"))
        self.verticalLayout_7.addWidget(self.cb_canvas_eyecandy)
        self.cb_canvas_use_opengl = QtGui.QCheckBox(self.groupBox_7)
        self.cb_canvas_use_opengl.setObjectName(_fromUtf8("cb_canvas_use_opengl"))
        self.verticalLayout_7.addWidget(self.cb_canvas_use_opengl)
        self.verticalLayout_8.addWidget(self.groupBox_7)
        self.groupBox_5 = QtGui.QGroupBox(self.page_canvas)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.cb_canvas_render_aa = QtGui.QCheckBox(self.groupBox_5)
        self.cb_canvas_render_aa.setTristate(True)
        self.cb_canvas_render_aa.setObjectName(_fromUtf8("cb_canvas_render_aa"))
        self.verticalLayout_9.addWidget(self.cb_canvas_render_aa)
        self.cb_canvas_render_hq_aa = QtGui.QCheckBox(self.groupBox_5)
        self.cb_canvas_render_hq_aa.setEnabled(False)
        self.cb_canvas_render_hq_aa.setObjectName(_fromUtf8("cb_canvas_render_hq_aa"))
        self.verticalLayout_9.addWidget(self.cb_canvas_render_hq_aa)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.stackedWidget.addWidget(self.page_canvas)
        self.page_ladish = QtGui.QWidget()
        self.page_ladish.setObjectName(_fromUtf8("page_ladish"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.page_ladish)
        self.verticalLayout_10.setMargin(2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_13 = QtGui.QLabel(self.page_ladish)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_11.addWidget(self.label_13)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.label_14 = QtGui.QLabel(self.page_ladish)
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/ladish.png")))
        self.label_14.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_11.addWidget(self.label_14)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.groupBox_6 = QtGui.QGroupBox(self.page_ladish)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.cb_ladish_studio_autostart = QtGui.QCheckBox(self.groupBox_6)
        self.cb_ladish_studio_autostart.setObjectName(_fromUtf8("cb_ladish_studio_autostart"))
        self.verticalLayout_6.addWidget(self.cb_ladish_studio_autostart)
        self.cb_ladish_notify = QtGui.QCheckBox(self.groupBox_6)
        self.cb_ladish_notify.setObjectName(_fromUtf8("cb_ladish_notify"))
        self.verticalLayout_6.addWidget(self.cb_ladish_notify)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_15 = QtGui.QLabel(self.page_ladish)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.le_ladish_shell = QtGui.QLineEdit(self.page_ladish)
        self.le_ladish_shell.setObjectName(_fromUtf8("le_ladish_shell"))
        self.gridLayout_3.addWidget(self.le_ladish_shell, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.page_ladish)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.le_ladish_terminal = QtGui.QLineEdit(self.page_ladish)
        self.le_ladish_terminal.setObjectName(_fromUtf8("le_ladish_terminal"))
        self.gridLayout_3.addWidget(self.le_ladish_terminal, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_ladish)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.sb_ladish_jsdelay = QtGui.QSpinBox(self.page_ladish)
        self.sb_ladish_jsdelay.setPrefix(_fromUtf8(""))
        self.sb_ladish_jsdelay.setMaximum(1000)
        self.sb_ladish_jsdelay.setObjectName(_fromUtf8("sb_ladish_jsdelay"))
        self.gridLayout_3.addWidget(self.sb_ladish_jsdelay, 2, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem9)
        self.stackedWidget.addWidget(self.page_ladish)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.stackedWidget.addWidget(self.page)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsW)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(SettingsW)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsW.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsW.reject)
        QtCore.QObject.connect(self.lw_page, QtCore.SIGNAL(_fromUtf8("currentCellChanged(int,int,int,int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.cb_canvas_use_opengl, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cb_canvas_render_hq_aa.setEnabled)
        QtCore.QObject.connect(self.cb_tray_enable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cb_tray_close_to.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SettingsW)

    def retranslateUi(self, SettingsW):
        SettingsW.setWindowTitle(_translate("SettingsW", "Settings", None))
        item = self.lw_page.verticalHeaderItem(0)
        item.setText(_translate("SettingsW", "main", None))
        item = self.lw_page.verticalHeaderItem(1)
        item.setText(_translate("SettingsW", "canvas", None))
        item = self.lw_page.verticalHeaderItem(2)
        item.setText(_translate("SettingsW", "ladish", None))
        item = self.lw_page.horizontalHeaderItem(0)
        item.setText(_translate("SettingsW", "Widget", None))
        __sortingEnabled = self.lw_page.isSortingEnabled()
        self.lw_page.setSortingEnabled(False)
        item = self.lw_page.item(0, 0)
        item.setText(_translate("SettingsW", "Main", None))
        item = self.lw_page.item(1, 0)
        item.setText(_translate("SettingsW", "Canvas", None))
        item = self.lw_page.item(2, 0)
        item.setText(_translate("SettingsW", "LADISH", None))
        self.lw_page.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("SettingsW", "<b>Main</b>", None))
        self.group_main_paths.setTitle(_translate("SettingsW", "Paths", None))
        self.label_3.setText(_translate("SettingsW", "Default project folder:", None))
        self.group_tray.setTitle(_translate("SettingsW", "System Tray", None))
        self.cb_tray_close_to.setText(_translate("SettingsW", "Close Main Window to System Tray", None))
        self.cb_tray_enable.setText(_translate("SettingsW", "Use System Tray (App-Indicator support)", None))
        self.groupBox_3.setTitle(_translate("SettingsW", "Misc", None))
        self.label_8.setText(_translate("SettingsW", "GUI Refresh interval:", None))
        self.sb_gui_refresh.setSuffix(_translate("SettingsW", " ms", None))
        self.label_jack_port_alias.setText(_translate("SettingsW", "JACK Port Aliases:", None))
        self.cb_jack_port_alias.setItemText(0, _translate("SettingsW", "0 (none)", None))
        self.cb_jack_port_alias.setItemText(1, _translate("SettingsW", "1st alias", None))
        self.cb_jack_port_alias.setItemText(2, _translate("SettingsW", "2nd alias", None))
        self.label_9.setText(_translate("SettingsW", "<b>Canvas</b>", None))
        self.groupBox_4.setTitle(_translate("SettingsW", "Theme", None))
        self.cb_canvas_bezier_lines.setText(_translate("SettingsW", "Bezier Lines", None))
        self.label_11.setText(_translate("SettingsW", "Theme:", None))
        self.groupBox_7.setTitle(_translate("SettingsW", "Options", None))
        self.cb_canvas_hide_groups.setText(_translate("SettingsW", "Auto-hide groups with no ports", None))
        self.cb_canvas_eyecandy.setText(_translate("SettingsW", "Fancy Eye-candy", None))
        self.cb_canvas_use_opengl.setText(_translate("SettingsW", "Use OpenGL for rendering (EXPERIMENTAL, needs restart)", None))
        self.groupBox_5.setTitle(_translate("SettingsW", "Render Hints", None))
        self.cb_canvas_render_aa.setText(_translate("SettingsW", "Antialiasing", None))
        self.cb_canvas_render_hq_aa.setText(_translate("SettingsW", "High Quality Antiliasing (OpenGL only)", None))
        self.label_13.setText(_translate("SettingsW", "<b>LADISH</b>", None))
        self.groupBox_6.setTitle(_translate("SettingsW", "Options", None))
        self.cb_ladish_studio_autostart.setText(_translate("SettingsW", "Start studio on load", None))
        self.cb_ladish_notify.setText(_translate("SettingsW", "Send notifications", None))
        self.label_15.setText(_translate("SettingsW", "Shell to use:", None))
        self.label_16.setText(_translate("SettingsW", "Terminal to use:", None))
        self.label_2.setText(_translate("SettingsW", "JS delay:", None))
        self.sb_ladish_jsdelay.setSuffix(_translate("SettingsW", " seconds", None))

import resources_rc
