# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/cadence.ui'
#
# Created: Tue Jul 11 07:46:41 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CadenceMainW(object):
    def setupUi(self, CadenceMainW):
        CadenceMainW.setObjectName(_fromUtf8("CadenceMainW"))
        CadenceMainW.resize(740, 564)
        self.centralwidget = QtGui.QWidget(CadenceMainW)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_system = QtGui.QWidget()
        self.tab_system.setObjectName(_fromUtf8("tab_system"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_system)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_welcome = QtGui.QLabel(self.tab_system)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_welcome.setFont(font)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName(_fromUtf8("label_welcome"))
        self.gridLayout_8.addWidget(self.label_welcome, 0, 0, 1, 3)
        self.line_welcome = QtGui.QFrame(self.tab_system)
        self.line_welcome.setLineWidth(0)
        self.line_welcome.setMidLineWidth(1)
        self.line_welcome.setFrameShape(QtGui.QFrame.HLine)
        self.line_welcome.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_welcome.setObjectName(_fromUtf8("line_welcome"))
        self.gridLayout_8.addWidget(self.line_welcome, 1, 0, 2, 3)
        self.line = QtGui.QFrame(self.tab_system)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_8.addWidget(self.line, 2, 1, 2, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_info = QtGui.QGroupBox(self.tab_system)
        self.groupBox_info.setObjectName(_fromUtf8("groupBox_info"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_info)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_info_os_L = QtGui.QLabel(self.groupBox_info)
        self.label_info_os_L.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_info_os_L.setObjectName(_fromUtf8("label_info_os_L"))
        self.gridLayout.addWidget(self.label_info_os_L, 0, 0, 1, 1)
        self.label_info_os = QtGui.QLabel(self.groupBox_info)
        self.label_info_os.setObjectName(_fromUtf8("label_info_os"))
        self.gridLayout.addWidget(self.label_info_os, 0, 1, 1, 1)
        self.label_info_version_L = QtGui.QLabel(self.groupBox_info)
        self.label_info_version_L.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_info_version_L.setObjectName(_fromUtf8("label_info_version_L"))
        self.gridLayout.addWidget(self.label_info_version_L, 1, 0, 1, 1)
        self.label_info_version = QtGui.QLabel(self.groupBox_info)
        self.label_info_version.setObjectName(_fromUtf8("label_info_version"))
        self.gridLayout.addWidget(self.label_info_version, 1, 1, 1, 1)
        self.label_info_arch_L = QtGui.QLabel(self.groupBox_info)
        self.label_info_arch_L.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_info_arch_L.setObjectName(_fromUtf8("label_info_arch_L"))
        self.gridLayout.addWidget(self.label_info_arch_L, 2, 0, 1, 1)
        self.label_info_arch = QtGui.QLabel(self.groupBox_info)
        self.label_info_arch.setObjectName(_fromUtf8("label_info_arch"))
        self.gridLayout.addWidget(self.label_info_arch, 2, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_info)
        self.groupBox_status = QtGui.QGroupBox(self.tab_system)
        self.groupBox_status.setObjectName(_fromUtf8("groupBox_status"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_status)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_cpufreq = QtGui.QLabel(self.groupBox_status)
        self.label_cpufreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cpufreq.setObjectName(_fromUtf8("label_cpufreq"))
        self.gridLayout_9.addWidget(self.label_cpufreq, 0, 0, 1, 1)
        self.cb_cpufreq = QtGui.QComboBox(self.groupBox_status)
        self.cb_cpufreq.setObjectName(_fromUtf8("cb_cpufreq"))
        self.gridLayout_9.addWidget(self.cb_cpufreq, 0, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_status)
        self.groupBox_checks = QtGui.QGroupBox(self.tab_system)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_checks.sizePolicy().hasHeightForWidth())
        self.groupBox_checks.setSizePolicy(sizePolicy)
        self.groupBox_checks.setObjectName(_fromUtf8("groupBox_checks"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_checks)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_check_helper2 = QtGui.QLabel(self.groupBox_checks)
        self.label_check_helper2.setText(_fromUtf8(""))
        self.label_check_helper2.setPixmap(QtGui.QPixmap(_fromUtf8(":/16x16/dialog-information.png")))
        self.label_check_helper2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_check_helper2.setObjectName(_fromUtf8("label_check_helper2"))
        self.gridLayout_3.addWidget(self.label_check_helper2, 0, 1, 1, 1)
        self.label_check_helper3 = QtGui.QLabel(self.groupBox_checks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_check_helper3.sizePolicy().hasHeightForWidth())
        self.label_check_helper3.setSizePolicy(sizePolicy)
        self.label_check_helper3.setObjectName(_fromUtf8("label_check_helper3"))
        self.gridLayout_3.addWidget(self.label_check_helper3, 0, 2, 1, 1)
        self.label_check_helper1 = QtGui.QLabel(self.groupBox_checks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_check_helper1.sizePolicy().hasHeightForWidth())
        self.label_check_helper1.setSizePolicy(sizePolicy)
        self.label_check_helper1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_check_helper1.setObjectName(_fromUtf8("label_check_helper1"))
        self.gridLayout_3.addWidget(self.label_check_helper1, 0, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.groupBox_checks)
        self.line_4.setLineWidth(0)
        self.line_4.setMidLineWidth(1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_3.addWidget(self.line_4, 1, 0, 1, 3)
        self.verticalLayout_10.addWidget(self.groupBox_checks)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.gridLayout_8.addLayout(self.verticalLayout_10, 3, 0, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.groupBox_jack = QtGui.QGroupBox(self.tab_system)
        self.groupBox_jack.setObjectName(_fromUtf8("groupBox_jack"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_jack)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.widget = QtGui.QWidget(self.groupBox_jack)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_jack_status_ico = QtGui.QLabel(self.widget)
        self.label_jack_status_ico.setText(_fromUtf8(""))
        self.label_jack_status_ico.setPixmap(QtGui.QPixmap(_fromUtf8(":/16x16/dialog-ok-apply.png")))
        self.label_jack_status_ico.setObjectName(_fromUtf8("label_jack_status_ico"))
        self.gridLayout_2.addWidget(self.label_jack_status_ico, 0, 1, 1, 1)
        self.label_jack_srate_L = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_jack_srate_L.sizePolicy().hasHeightForWidth())
        self.label_jack_srate_L.setSizePolicy(sizePolicy)
        self.label_jack_srate_L.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jack_srate_L.setObjectName(_fromUtf8("label_jack_srate_L"))
        self.gridLayout_2.addWidget(self.label_jack_srate_L, 5, 0, 1, 1)
        self.label_jack_dsp_L = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_jack_dsp_L.sizePolicy().hasHeightForWidth())
        self.label_jack_dsp_L.setSizePolicy(sizePolicy)
        self.label_jack_dsp_L.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jack_dsp_L.setObjectName(_fromUtf8("label_jack_dsp_L"))
        self.gridLayout_2.addWidget(self.label_jack_dsp_L, 2, 0, 1, 1)
        self.label_jack_realtime = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_jack_realtime.sizePolicy().hasHeightForWidth())
        self.label_jack_realtime.setSizePolicy(sizePolicy)
        self.label_jack_realtime.setObjectName(_fromUtf8("label_jack_realtime"))
        self.gridLayout_2.addWidget(self.label_jack_realtime, 1, 2, 1, 1)
        self.label_jack_realtime_L = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_jack_realtime_L.sizePolicy().hasHeightForWidth())
        self.label_jack_realtime_L.setSizePolicy(sizePolicy)
        self.label_jack_realtime_L.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jack_realtime_L.setObjectName(_fromUtf8("label_jack_realtime_L"))
        self.gridLayout_2.addWidget(self.label_jack_realtime_L, 1, 0, 1, 1)
        self.label_jack_realtime_ico = QtGui.QLabel(self.widget)
        self.label_jack_realtime_ico.setText(_fromUtf8(""))
        self.label_jack_realtime_ico.setPixmap(QtGui.QPixmap(_fromUtf8(":/16x16/dialog-ok-apply.png")))
        self.label_jack_realtime_ico.setAlignment(QtCore.Qt.AlignCenter)
        self.label_jack_realtime_ico.setObjectName(_fromUtf8("label_jack_realtime_ico"))
        self.gridLayout_2.addWidget(self.label_jack_realtime_ico, 1, 1, 1, 1)
        self.label_jack_bufsize_L = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_jack_bufsize_L.sizePolicy().hasHeightForWidth())
        self.label_jack_bufsize_L.setSizePolicy(sizePolicy)
        self.label_jack_bufsize_L.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jack_bufsize_L.setObjectName(_fromUtf8("label_jack_bufsize_L"))
        self.gridLayout_2.addWidget(self.label_jack_bufsize_L, 4, 0, 1, 1)
        self.label_jack_dsp = QtGui.QLabel(self.widget)
        self.label_jack_dsp.setObjectName(_fromUtf8("label_jack_dsp"))
        self.gridLayout_2.addWidget(self.label_jack_dsp, 2, 1, 1, 2)
        self.label_jack_xruns_L = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_jack_xruns_L.sizePolicy().hasHeightForWidth())
        self.label_jack_xruns_L.setSizePolicy(sizePolicy)
        self.label_jack_xruns_L.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jack_xruns_L.setObjectName(_fromUtf8("label_jack_xruns_L"))
        self.gridLayout_2.addWidget(self.label_jack_xruns_L, 3, 0, 1, 1)
        self.label_jack_status = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_jack_status.sizePolicy().hasHeightForWidth())
        self.label_jack_status.setSizePolicy(sizePolicy)
        self.label_jack_status.setObjectName(_fromUtf8("label_jack_status"))
        self.gridLayout_2.addWidget(self.label_jack_status, 0, 2, 1, 1)
        self.label_jack_status_L = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_jack_status_L.sizePolicy().hasHeightForWidth())
        self.label_jack_status_L.setSizePolicy(sizePolicy)
        self.label_jack_status_L.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jack_status_L.setObjectName(_fromUtf8("label_jack_status_L"))
        self.gridLayout_2.addWidget(self.label_jack_status_L, 0, 0, 1, 1)
        self.label_jack_latency_L = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_jack_latency_L.sizePolicy().hasHeightForWidth())
        self.label_jack_latency_L.setSizePolicy(sizePolicy)
        self.label_jack_latency_L.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_jack_latency_L.setObjectName(_fromUtf8("label_jack_latency_L"))
        self.gridLayout_2.addWidget(self.label_jack_latency_L, 6, 0, 1, 1)
        self.label_jack_xruns = QtGui.QLabel(self.widget)
        self.label_jack_xruns.setObjectName(_fromUtf8("label_jack_xruns"))
        self.gridLayout_2.addWidget(self.label_jack_xruns, 3, 1, 1, 2)
        self.label_jack_bfsize = QtGui.QLabel(self.widget)
        self.label_jack_bfsize.setObjectName(_fromUtf8("label_jack_bfsize"))
        self.gridLayout_2.addWidget(self.label_jack_bfsize, 4, 1, 1, 2)
        self.label_jack_srate = QtGui.QLabel(self.widget)
        self.label_jack_srate.setObjectName(_fromUtf8("label_jack_srate"))
        self.gridLayout_2.addWidget(self.label_jack_srate, 5, 1, 1, 2)
        self.label_jack_latency = QtGui.QLabel(self.widget)
        self.label_jack_latency.setObjectName(_fromUtf8("label_jack_latency"))
        self.gridLayout_2.addWidget(self.label_jack_latency, 6, 1, 1, 2)
        self.verticalLayout_9.addWidget(self.widget)
        self.line_2 = QtGui.QFrame(self.groupBox_jack)
        self.line_2.setLineWidth(0)
        self.line_2.setMidLineWidth(1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_9.addWidget(self.line_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.b_jack_start = QtGui.QPushButton(self.groupBox_jack)
        self.b_jack_start.setObjectName(_fromUtf8("b_jack_start"))
        self.gridLayout_4.addWidget(self.b_jack_start, 0, 0, 1, 1)
        self.b_jack_stop = QtGui.QPushButton(self.groupBox_jack)
        self.b_jack_stop.setObjectName(_fromUtf8("b_jack_stop"))
        self.gridLayout_4.addWidget(self.b_jack_stop, 0, 1, 1, 2)
        self.b_jack_restart = QtGui.QPushButton(self.groupBox_jack)
        self.b_jack_restart.setObjectName(_fromUtf8("b_jack_restart"))
        self.gridLayout_4.addWidget(self.b_jack_restart, 0, 3, 1, 1)
        self.b_jack_configure = QtGui.QPushButton(self.groupBox_jack)
        self.b_jack_configure.setObjectName(_fromUtf8("b_jack_configure"))
        self.gridLayout_4.addWidget(self.b_jack_configure, 0, 4, 1, 2)
        self.b_jack_switchmaster = QtGui.QPushButton(self.groupBox_jack)
        self.b_jack_switchmaster.setObjectName(_fromUtf8("b_jack_switchmaster"))
        self.gridLayout_4.addWidget(self.b_jack_switchmaster, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(38, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        self.cb_jack_autostart = QtGui.QCheckBox(self.groupBox_jack)
        self.cb_jack_autostart.setObjectName(_fromUtf8("cb_jack_autostart"))
        self.gridLayout_4.addWidget(self.cb_jack_autostart, 1, 2, 1, 3)
        self.tb_jack_options = QtGui.QToolButton(self.groupBox_jack)
        self.tb_jack_options.setObjectName(_fromUtf8("tb_jack_options"))
        self.gridLayout_4.addWidget(self.tb_jack_options, 1, 5, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_4)
        self.verticalLayout_12.addWidget(self.groupBox_jack)
        self.groupBox_bridges = QtGui.QGroupBox(self.tab_system)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_bridges.sizePolicy().hasHeightForWidth())
        self.groupBox_bridges.setSizePolicy(sizePolicy)
        self.groupBox_bridges.setObjectName(_fromUtf8("groupBox_bridges"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_bridges)
        self.gridLayout_5.setMargin(2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.toolBox_2 = QtGui.QToolBox(self.groupBox_bridges)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_2.sizePolicy().hasHeightForWidth())
        self.toolBox_2.setSizePolicy(sizePolicy)
        self.toolBox_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.toolBox_2.setLineWidth(0)
        self.toolBox_2.setMidLineWidth(1)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.toolBox_alsaaudio = QtGui.QWidget()
        self.toolBox_alsaaudio.setGeometry(QtCore.QRect(0, 0, 360, 100))
        self.toolBox_alsaaudio.setObjectName(_fromUtf8("toolBox_alsaaudio"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.toolBox_alsaaudio)
        self.verticalLayout_18.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_bridge_alsa = QtGui.QLabel(self.toolBox_alsaaudio)
        self.label_bridge_alsa.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bridge_alsa.setObjectName(_fromUtf8("label_bridge_alsa"))
        self.verticalLayout_18.addWidget(self.label_bridge_alsa)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.b_alsa_start = QtGui.QPushButton(self.toolBox_alsaaudio)
        self.b_alsa_start.setObjectName(_fromUtf8("b_alsa_start"))
        self.horizontalLayout_8.addWidget(self.b_alsa_start)
        self.b_alsa_stop = QtGui.QPushButton(self.toolBox_alsaaudio)
        self.b_alsa_stop.setObjectName(_fromUtf8("b_alsa_stop"))
        self.horizontalLayout_8.addWidget(self.b_alsa_stop)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_18.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.toolBox_alsaaudio)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.cb_alsa_type = QtGui.QComboBox(self.toolBox_alsaaudio)
        self.cb_alsa_type.setObjectName(_fromUtf8("cb_alsa_type"))
        self.cb_alsa_type.addItem(_fromUtf8(""))
        self.cb_alsa_type.addItem(_fromUtf8(""))
        self.cb_alsa_type.addItem(_fromUtf8(""))
        self.cb_alsa_type.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.cb_alsa_type)
        self.tb_alsa_options = QtGui.QToolButton(self.toolBox_alsaaudio)
        self.tb_alsa_options.setObjectName(_fromUtf8("tb_alsa_options"))
        self.horizontalLayout_7.addWidget(self.tb_alsa_options)
        self.verticalLayout_18.addLayout(self.horizontalLayout_7)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_18.addItem(spacerItem4)
        self.toolBox_2.addItem(self.toolBox_alsaaudio, _fromUtf8(""))
        self.toolBox_alsamidi = QtGui.QWidget()
        self.toolBox_alsamidi.setGeometry(QtCore.QRect(0, 0, 360, 97))
        self.toolBox_alsamidi.setObjectName(_fromUtf8("toolBox_alsamidi"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.toolBox_alsamidi)
        self.verticalLayout_20.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_bridge_a2j = QtGui.QLabel(self.toolBox_alsamidi)
        self.label_bridge_a2j.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bridge_a2j.setObjectName(_fromUtf8("label_bridge_a2j"))
        self.verticalLayout_20.addWidget(self.label_bridge_a2j)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem5 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.b_a2j_start = QtGui.QPushButton(self.toolBox_alsamidi)
        self.b_a2j_start.setObjectName(_fromUtf8("b_a2j_start"))
        self.horizontalLayout_9.addWidget(self.b_a2j_start)
        self.b_a2j_stop = QtGui.QPushButton(self.toolBox_alsamidi)
        self.b_a2j_stop.setObjectName(_fromUtf8("b_a2j_stop"))
        self.horizontalLayout_9.addWidget(self.b_a2j_stop)
        self.b_a2j_export_hw = QtGui.QPushButton(self.toolBox_alsamidi)
        self.b_a2j_export_hw.setObjectName(_fromUtf8("b_a2j_export_hw"))
        self.horizontalLayout_9.addWidget(self.b_a2j_export_hw)
        spacerItem6 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_20.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.cb_a2j_autostart = QtGui.QCheckBox(self.toolBox_alsamidi)
        self.cb_a2j_autostart.setObjectName(_fromUtf8("cb_a2j_autostart"))
        self.horizontalLayout_11.addWidget(self.cb_a2j_autostart)
        self.tb_a2j_options = QtGui.QToolButton(self.toolBox_alsamidi)
        self.tb_a2j_options.setObjectName(_fromUtf8("tb_a2j_options"))
        self.horizontalLayout_11.addWidget(self.tb_a2j_options)
        self.verticalLayout_20.addLayout(self.horizontalLayout_11)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_20.addItem(spacerItem8)
        self.toolBox_2.addItem(self.toolBox_alsamidi, _fromUtf8(""))
        self.toolBox_pulseaudio = QtGui.QWidget()
        self.toolBox_pulseaudio.setGeometry(QtCore.QRect(0, 0, 360, 97))
        self.toolBox_pulseaudio.setObjectName(_fromUtf8("toolBox_pulseaudio"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.toolBox_pulseaudio)
        self.verticalLayout_19.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_bridge_pulse = QtGui.QLabel(self.toolBox_pulseaudio)
        self.label_bridge_pulse.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bridge_pulse.setObjectName(_fromUtf8("label_bridge_pulse"))
        self.verticalLayout_19.addWidget(self.label_bridge_pulse)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem9 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.b_pulse_start = QtGui.QPushButton(self.toolBox_pulseaudio)
        self.b_pulse_start.setObjectName(_fromUtf8("b_pulse_start"))
        self.horizontalLayout_10.addWidget(self.b_pulse_start)
        self.b_pulse_stop = QtGui.QPushButton(self.toolBox_pulseaudio)
        self.b_pulse_stop.setObjectName(_fromUtf8("b_pulse_stop"))
        self.horizontalLayout_10.addWidget(self.b_pulse_stop)
        spacerItem10 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.verticalLayout_19.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.cb_pulse_autostart = QtGui.QCheckBox(self.toolBox_pulseaudio)
        self.cb_pulse_autostart.setObjectName(_fromUtf8("cb_pulse_autostart"))
        self.horizontalLayout_12.addWidget(self.cb_pulse_autostart)
        self.tb_pulse_options = QtGui.QToolButton(self.toolBox_pulseaudio)
        self.tb_pulse_options.setObjectName(_fromUtf8("tb_pulse_options"))
        self.horizontalLayout_12.addWidget(self.tb_pulse_options)
        self.verticalLayout_19.addLayout(self.horizontalLayout_12)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_19.addItem(spacerItem12)
        self.toolBox_2.addItem(self.toolBox_pulseaudio, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.toolBox_2, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_bridges)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_12.addItem(spacerItem13)
        self.gridLayout_8.addLayout(self.verticalLayout_12, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab_system, _fromUtf8(""))
        self.tab_tools = QtGui.QWidget()
        self.tab_tools.setObjectName(_fromUtf8("tab_tools"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_tools)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_tools_apps = QtGui.QLabel(self.tab_tools)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_tools_apps.setFont(font)
        self.label_tools_apps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tools_apps.setObjectName(_fromUtf8("label_tools_apps"))
        self.verticalLayout_8.addWidget(self.label_tools_apps)
        self.line_tools_apps = QtGui.QFrame(self.tab_tools)
        self.line_tools_apps.setLineWidth(0)
        self.line_tools_apps.setMidLineWidth(1)
        self.line_tools_apps.setFrameShape(QtGui.QFrame.HLine)
        self.line_tools_apps.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_tools_apps.setObjectName(_fromUtf8("line_tools_apps"))
        self.verticalLayout_8.addWidget(self.line_tools_apps)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_catia = QtGui.QGroupBox(self.tab_tools)
        self.groupBox_catia.setObjectName(_fromUtf8("groupBox_catia"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_catia)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pic_catia = ClickableLabel(self.groupBox_catia)
        self.pic_catia.setMinimumSize(QtCore.QSize(0, 117))
        self.pic_catia.setMaximumSize(QtCore.QSize(16777215, 117))
        self.pic_catia.setText(_fromUtf8(""))
        self.pic_catia.setPixmap(QtGui.QPixmap(_fromUtf8(":/screens/catia.png")))
        self.pic_catia.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_catia.setObjectName(_fromUtf8("pic_catia"))
        self.verticalLayout_2.addWidget(self.pic_catia)
        self.label_tools_catia = QtGui.QLabel(self.groupBox_catia)
        self.label_tools_catia.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tools_catia.setWordWrap(True)
        self.label_tools_catia.setObjectName(_fromUtf8("label_tools_catia"))
        self.verticalLayout_2.addWidget(self.label_tools_catia)
        self.horizontalLayout_3.addWidget(self.groupBox_catia)
        self.groupBox_claudia = QtGui.QGroupBox(self.tab_tools)
        self.groupBox_claudia.setObjectName(_fromUtf8("groupBox_claudia"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_claudia)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pic_claudia = ClickableLabel(self.groupBox_claudia)
        self.pic_claudia.setMinimumSize(QtCore.QSize(0, 117))
        self.pic_claudia.setMaximumSize(QtCore.QSize(16777215, 117))
        self.pic_claudia.setText(_fromUtf8(""))
        self.pic_claudia.setPixmap(QtGui.QPixmap(_fromUtf8(":/screens/claudia.png")))
        self.pic_claudia.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_claudia.setObjectName(_fromUtf8("pic_claudia"))
        self.verticalLayout_3.addWidget(self.pic_claudia)
        self.label_tools_claudia = QtGui.QLabel(self.groupBox_claudia)
        self.label_tools_claudia.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tools_claudia.setWordWrap(True)
        self.label_tools_claudia.setObjectName(_fromUtf8("label_tools_claudia"))
        self.verticalLayout_3.addWidget(self.label_tools_claudia)
        self.horizontalLayout_3.addWidget(self.groupBox_claudia)
        self.groupBox_meter = QtGui.QGroupBox(self.tab_tools)
        self.groupBox_meter.setObjectName(_fromUtf8("groupBox_meter"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_meter)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pic_meter_in = ClickableLabel(self.groupBox_meter)
        self.pic_meter_in.setText(_fromUtf8(""))
        self.pic_meter_in.setPixmap(QtGui.QPixmap(_fromUtf8(":/screens/cadence-jackmeter-in.png")))
        self.pic_meter_in.setObjectName(_fromUtf8("pic_meter_in"))
        self.horizontalLayout_5.addWidget(self.pic_meter_in)
        self.pic_meter_out = ClickableLabel(self.groupBox_meter)
        self.pic_meter_out.setMinimumSize(QtCore.QSize(0, 117))
        self.pic_meter_out.setMaximumSize(QtCore.QSize(16777215, 117))
        self.pic_meter_out.setText(_fromUtf8(""))
        self.pic_meter_out.setPixmap(QtGui.QPixmap(_fromUtf8(":/screens/cadence-jackmeter-out.png")))
        self.pic_meter_out.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_meter_out.setObjectName(_fromUtf8("pic_meter_out"))
        self.horizontalLayout_5.addWidget(self.pic_meter_out)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.label_tools_meter = QtGui.QLabel(self.groupBox_meter)
        self.label_tools_meter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tools_meter.setWordWrap(True)
        self.label_tools_meter.setObjectName(_fromUtf8("label_tools_meter"))
        self.verticalLayout_4.addWidget(self.label_tools_meter)
        self.horizontalLayout_3.addWidget(self.groupBox_meter)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        spacerItem14 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem14)
        self.label_tools_tools = QtGui.QLabel(self.tab_tools)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_tools_tools.setFont(font)
        self.label_tools_tools.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tools_tools.setObjectName(_fromUtf8("label_tools_tools"))
        self.verticalLayout_8.addWidget(self.label_tools_tools)
        self.line_tools_tools = QtGui.QFrame(self.tab_tools)
        self.line_tools_tools.setLineWidth(0)
        self.line_tools_tools.setMidLineWidth(1)
        self.line_tools_tools.setFrameShape(QtGui.QFrame.HLine)
        self.line_tools_tools.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_tools_tools.setObjectName(_fromUtf8("line_tools_tools"))
        self.verticalLayout_8.addWidget(self.line_tools_tools)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_logs = QtGui.QGroupBox(self.tab_tools)
        self.groupBox_logs.setObjectName(_fromUtf8("groupBox_logs"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_logs)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.pic_logs = ClickableLabel(self.groupBox_logs)
        self.pic_logs.setMinimumSize(QtCore.QSize(0, 128))
        self.pic_logs.setMaximumSize(QtCore.QSize(16777215, 128))
        self.pic_logs.setText(_fromUtf8(""))
        self.pic_logs.setPixmap(QtGui.QPixmap(_fromUtf8(":/screens/cadence-logs.png")))
        self.pic_logs.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_logs.setObjectName(_fromUtf8("pic_logs"))
        self.verticalLayout_7.addWidget(self.pic_logs)
        self.label_tools_logs = QtGui.QLabel(self.groupBox_logs)
        self.label_tools_logs.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tools_logs.setWordWrap(True)
        self.label_tools_logs.setObjectName(_fromUtf8("label_tools_logs"))
        self.verticalLayout_7.addWidget(self.label_tools_logs)
        self.horizontalLayout_4.addWidget(self.groupBox_logs)
        self.groupBox_render = QtGui.QGroupBox(self.tab_tools)
        self.groupBox_render.setObjectName(_fromUtf8("groupBox_render"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_render)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pic_render = ClickableLabel(self.groupBox_render)
        self.pic_render.setMinimumSize(QtCore.QSize(0, 128))
        self.pic_render.setMaximumSize(QtCore.QSize(16777215, 128))
        self.pic_render.setText(_fromUtf8(""))
        self.pic_render.setPixmap(QtGui.QPixmap(_fromUtf8(":/screens/cadence-render.png")))
        self.pic_render.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_render.setObjectName(_fromUtf8("pic_render"))
        self.verticalLayout_6.addWidget(self.pic_render)
        self.label_tools_render = QtGui.QLabel(self.groupBox_render)
        self.label_tools_render.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tools_render.setWordWrap(True)
        self.label_tools_render.setObjectName(_fromUtf8("label_tools_render"))
        self.verticalLayout_6.addWidget(self.label_tools_render)
        self.horizontalLayout_4.addWidget(self.groupBox_render)
        self.groupBox_xycontroller = QtGui.QGroupBox(self.tab_tools)
        self.groupBox_xycontroller.setObjectName(_fromUtf8("groupBox_xycontroller"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_xycontroller)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pic_xycontroller = ClickableLabel(self.groupBox_xycontroller)
        self.pic_xycontroller.setMinimumSize(QtCore.QSize(0, 128))
        self.pic_xycontroller.setMaximumSize(QtCore.QSize(16777215, 128))
        self.pic_xycontroller.setText(_fromUtf8(""))
        self.pic_xycontroller.setPixmap(QtGui.QPixmap(_fromUtf8(":/screens/cadence-xycontroller.png")))
        self.pic_xycontroller.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_xycontroller.setObjectName(_fromUtf8("pic_xycontroller"))
        self.verticalLayout_5.addWidget(self.pic_xycontroller)
        self.label_tools_xycontroller = QtGui.QLabel(self.groupBox_xycontroller)
        self.label_tools_xycontroller.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tools_xycontroller.setWordWrap(True)
        self.label_tools_xycontroller.setObjectName(_fromUtf8("label_tools_xycontroller"))
        self.verticalLayout_5.addWidget(self.label_tools_xycontroller)
        self.horizontalLayout_4.addWidget(self.groupBox_xycontroller)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        spacerItem15 = QtGui.QSpacerItem(20, 94, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem15)
        self.tabWidget.addTab(self.tab_tools, _fromUtf8(""))
        self.tab_tweaks = QtGui.QWidget()
        self.tab_tweaks.setObjectName(_fromUtf8("tab_tweaks"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.tab_tweaks)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_tweaks = QtGui.QLabel(self.tab_tweaks)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_tweaks.setFont(font)
        self.label_tweaks.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tweaks.setObjectName(_fromUtf8("label_tweaks"))
        self.verticalLayout_15.addWidget(self.label_tweaks)
        self.line_tweaks = QtGui.QFrame(self.tab_tweaks)
        self.line_tweaks.setLineWidth(0)
        self.line_tweaks.setMidLineWidth(1)
        self.line_tweaks.setFrameShape(QtGui.QFrame.HLine)
        self.line_tweaks.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_tweaks.setObjectName(_fromUtf8("line_tweaks"))
        self.verticalLayout_15.addWidget(self.line_tweaks)
        self.frame_tweaks_settings = QtGui.QFrame(self.tab_tweaks)
        self.frame_tweaks_settings.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_tweaks_settings.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_tweaks_settings.setObjectName(_fromUtf8("frame_tweaks_settings"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_tweaks_settings)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem16 = QtGui.QSpacerItem(236, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)
        self.label_2 = QtGui.QLabel(self.frame_tweaks_settings)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem17 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.b_tweaks_apply_now = QtGui.QPushButton(self.frame_tweaks_settings)
        self.b_tweaks_apply_now.setObjectName(_fromUtf8("b_tweaks_apply_now"))
        self.horizontalLayout_2.addWidget(self.b_tweaks_apply_now)
        spacerItem18 = QtGui.QSpacerItem(235, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem18)
        self.verticalLayout_15.addWidget(self.frame_tweaks_settings)
        self.splitter = QtGui.QSplitter(self.tab_tweaks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tw_tweaks = QtGui.QTableWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tw_tweaks.sizePolicy().hasHeightForWidth())
        self.tw_tweaks.setSizePolicy(sizePolicy)
        self.tw_tweaks.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tw_tweaks.setObjectName(_fromUtf8("tw_tweaks"))
        self.tw_tweaks.setColumnCount(1)
        self.tw_tweaks.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tw_tweaks.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tw_tweaks.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tw_tweaks.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tw_tweaks.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tw_tweaks.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tw_tweaks.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tw_tweaks.setItem(2, 0, item)
        self.tw_tweaks.horizontalHeader().setVisible(False)
        self.tw_tweaks.horizontalHeader().setStretchLastSection(True)
        self.tw_tweaks.verticalHeader().setVisible(False)
        self.sw_tweaks = QtGui.QStackedWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sw_tweaks.sizePolicy().hasHeightForWidth())
        self.sw_tweaks.setSizePolicy(sizePolicy)
        self.sw_tweaks.setObjectName(_fromUtf8("sw_tweaks"))
        self.page_plugins = QtGui.QWidget()
        self.page_plugins.setObjectName(_fromUtf8("page_plugins"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page_plugins)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.b_tweak_plugins_remove = QtGui.QPushButton(self.page_plugins)
        self.b_tweak_plugins_remove.setObjectName(_fromUtf8("b_tweak_plugins_remove"))
        self.gridLayout_6.addWidget(self.b_tweak_plugins_remove, 3, 1, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem19, 4, 1, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 220, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem20, 7, 1, 1, 1)
        self.b_tweak_plugins_add = QtGui.QPushButton(self.page_plugins)
        self.b_tweak_plugins_add.setObjectName(_fromUtf8("b_tweak_plugins_add"))
        self.gridLayout_6.addWidget(self.b_tweak_plugins_add, 1, 1, 1, 1)
        self.tb_tweak_plugins = QtGui.QToolBox(self.page_plugins)
        self.tb_tweak_plugins.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tb_tweak_plugins.setFrameShadow(QtGui.QFrame.Sunken)
        self.tb_tweak_plugins.setLineWidth(0)
        self.tb_tweak_plugins.setMidLineWidth(1)
        self.tb_tweak_plugins.setObjectName(_fromUtf8("tb_tweak_plugins"))
        self.page_ladspa = QtGui.QWidget()
        self.page_ladspa.setGeometry(QtCore.QRect(0, 0, 416, 334))
        self.page_ladspa.setObjectName(_fromUtf8("page_ladspa"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_ladspa)
        self.verticalLayout.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.list_LADSPA = QtGui.QListWidget(self.page_ladspa)
        self.list_LADSPA.setObjectName(_fromUtf8("list_LADSPA"))
        self.verticalLayout.addWidget(self.list_LADSPA)
        self.tb_tweak_plugins.addItem(self.page_ladspa, _fromUtf8(""))
        self.page_dssi = QtGui.QWidget()
        self.page_dssi.setGeometry(QtCore.QRect(0, 0, 94, 66))
        self.page_dssi.setObjectName(_fromUtf8("page_dssi"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page_dssi)
        self.verticalLayout_11.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.list_DSSI = QtGui.QListWidget(self.page_dssi)
        self.list_DSSI.setObjectName(_fromUtf8("list_DSSI"))
        self.verticalLayout_11.addWidget(self.list_DSSI)
        self.tb_tweak_plugins.addItem(self.page_dssi, _fromUtf8(""))
        self.page_lv2 = QtGui.QWidget()
        self.page_lv2.setGeometry(QtCore.QRect(0, 0, 94, 66))
        self.page_lv2.setObjectName(_fromUtf8("page_lv2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.page_lv2)
        self.verticalLayout_13.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.list_LV2 = QtGui.QListWidget(self.page_lv2)
        self.list_LV2.setObjectName(_fromUtf8("list_LV2"))
        self.verticalLayout_13.addWidget(self.list_LV2)
        self.tb_tweak_plugins.addItem(self.page_lv2, _fromUtf8(""))
        self.page_vst = QtGui.QWidget()
        self.page_vst.setGeometry(QtCore.QRect(0, 0, 94, 66))
        self.page_vst.setObjectName(_fromUtf8("page_vst"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.page_vst)
        self.verticalLayout_14.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.list_VST = QtGui.QListWidget(self.page_vst)
        self.list_VST.setObjectName(_fromUtf8("list_VST"))
        self.verticalLayout_14.addWidget(self.list_VST)
        self.tb_tweak_plugins.addItem(self.page_vst, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tb_tweak_plugins, 0, 0, 8, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem21, 0, 1, 1, 1)
        self.b_tweak_plugins_reset = QtGui.QPushButton(self.page_plugins)
        self.b_tweak_plugins_reset.setObjectName(_fromUtf8("b_tweak_plugins_reset"))
        self.gridLayout_6.addWidget(self.b_tweak_plugins_reset, 6, 1, 1, 1)
        self.b_tweak_plugins_change = QtGui.QPushButton(self.page_plugins)
        self.b_tweak_plugins_change.setObjectName(_fromUtf8("b_tweak_plugins_change"))
        self.gridLayout_6.addWidget(self.b_tweak_plugins_change, 2, 1, 1, 1)
        self.sw_tweaks.addWidget(self.page_plugins)
        self.page_apps = QtGui.QWidget()
        self.page_apps.setObjectName(_fromUtf8("page_apps"))
        self.gridLayout_7 = QtGui.QGridLayout(self.page_apps)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setVerticalSpacing(20)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.ch_app_image = QtGui.QCheckBox(self.page_apps)
        self.ch_app_image.setObjectName(_fromUtf8("ch_app_image"))
        self.gridLayout_7.addWidget(self.ch_app_image, 1, 0, 1, 1)
        self.cb_app_video = QtGui.QComboBox(self.page_apps)
        self.cb_app_video.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_app_video.sizePolicy().hasHeightForWidth())
        self.cb_app_video.setSizePolicy(sizePolicy)
        self.cb_app_video.setObjectName(_fromUtf8("cb_app_video"))
        self.gridLayout_7.addWidget(self.cb_app_video, 3, 1, 1, 1)
        self.ch_app_text = QtGui.QCheckBox(self.page_apps)
        self.ch_app_text.setObjectName(_fromUtf8("ch_app_text"))
        self.gridLayout_7.addWidget(self.ch_app_text, 4, 0, 1, 1)
        self.cb_app_text = QtGui.QComboBox(self.page_apps)
        self.cb_app_text.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_app_text.sizePolicy().hasHeightForWidth())
        self.cb_app_text.setSizePolicy(sizePolicy)
        self.cb_app_text.setObjectName(_fromUtf8("cb_app_text"))
        self.gridLayout_7.addWidget(self.cb_app_text, 4, 1, 1, 1)
        self.ch_app_video = QtGui.QCheckBox(self.page_apps)
        self.ch_app_video.setObjectName(_fromUtf8("ch_app_video"))
        self.gridLayout_7.addWidget(self.ch_app_video, 3, 0, 1, 1)
        self.cb_app_browser = QtGui.QComboBox(self.page_apps)
        self.cb_app_browser.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_app_browser.sizePolicy().hasHeightForWidth())
        self.cb_app_browser.setSizePolicy(sizePolicy)
        self.cb_app_browser.setObjectName(_fromUtf8("cb_app_browser"))
        self.gridLayout_7.addWidget(self.cb_app_browser, 5, 1, 1, 1)
        self.ch_app_music = QtGui.QCheckBox(self.page_apps)
        self.ch_app_music.setObjectName(_fromUtf8("ch_app_music"))
        self.gridLayout_7.addWidget(self.ch_app_music, 2, 0, 1, 1)
        self.cb_app_music = QtGui.QComboBox(self.page_apps)
        self.cb_app_music.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_app_music.sizePolicy().hasHeightForWidth())
        self.cb_app_music.setSizePolicy(sizePolicy)
        self.cb_app_music.setObjectName(_fromUtf8("cb_app_music"))
        self.gridLayout_7.addWidget(self.cb_app_music, 2, 1, 1, 1)
        self.ch_app_browser = QtGui.QCheckBox(self.page_apps)
        self.ch_app_browser.setObjectName(_fromUtf8("ch_app_browser"))
        self.gridLayout_7.addWidget(self.ch_app_browser, 5, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 114, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem22, 6, 1, 1, 1)
        self.cb_app_image = QtGui.QComboBox(self.page_apps)
        self.cb_app_image.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_app_image.sizePolicy().hasHeightForWidth())
        self.cb_app_image.setSizePolicy(sizePolicy)
        self.cb_app_image.setObjectName(_fromUtf8("cb_app_image"))
        self.gridLayout_7.addWidget(self.cb_app_image, 1, 1, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem23, 0, 1, 1, 1)
        self.frame_app = QtGui.QFrame(self.page_apps)
        self.frame_app.setMinimumSize(QtCore.QSize(156, 0))
        self.frame_app.setMaximumSize(QtCore.QSize(156, 16777215))
        self.frame_app.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_app.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_app.setObjectName(_fromUtf8("frame_app"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.frame_app)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.ico_app = QtGui.QLabel(self.frame_app)
        self.ico_app.setMinimumSize(QtCore.QSize(48, 48))
        self.ico_app.setText(_fromUtf8(""))
        self.ico_app.setPixmap(QtGui.QPixmap(_fromUtf8(":/48x48/exec.png")))
        self.ico_app.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ico_app.setObjectName(_fromUtf8("ico_app"))
        self.verticalLayout_16.addWidget(self.ico_app)
        self.label_app_name = QtGui.QLabel(self.frame_app)
        self.label_app_name.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_app_name.setObjectName(_fromUtf8("label_app_name"))
        self.verticalLayout_16.addWidget(self.label_app_name)
        self.line_3 = QtGui.QFrame(self.frame_app)
        self.line_3.setLineWidth(0)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_16.addWidget(self.line_3)
        self.label_app_comment = QtGui.QLabel(self.frame_app)
        self.label_app_comment.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_app_comment.setWordWrap(True)
        self.label_app_comment.setObjectName(_fromUtf8("label_app_comment"))
        self.verticalLayout_16.addWidget(self.label_app_comment)
        spacerItem24 = QtGui.QSpacerItem(20, 287, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem24)
        self.gridLayout_7.addWidget(self.frame_app, 0, 2, 7, 1)
        self.sw_tweaks.addWidget(self.page_apps)
        self.page_wineasio = QtGui.QWidget()
        self.page_wineasio.setObjectName(_fromUtf8("page_wineasio"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.page_wineasio)
        self.verticalLayout_17.setMargin(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.groupBox_7 = QtGui.QGroupBox(self.page_wineasio)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_7 = QtGui.QLabel(self.groupBox_7)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_20.addWidget(self.label_7)
        self.sb_wineasio_ins = QtGui.QSpinBox(self.groupBox_7)
        self.sb_wineasio_ins.setMaximum(128)
        self.sb_wineasio_ins.setSingleStep(2)
        self.sb_wineasio_ins.setObjectName(_fromUtf8("sb_wineasio_ins"))
        self.horizontalLayout_20.addWidget(self.sb_wineasio_ins)
        self.verticalLayout_22.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_21 = QtGui.QLabel(self.groupBox_7)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_19.addWidget(self.label_21)
        self.sb_wineasio_outs = QtGui.QSpinBox(self.groupBox_7)
        self.sb_wineasio_outs.setMinimum(2)
        self.sb_wineasio_outs.setMaximum(128)
        self.sb_wineasio_outs.setSingleStep(2)
        self.sb_wineasio_outs.setObjectName(_fromUtf8("sb_wineasio_outs"))
        self.horizontalLayout_19.addWidget(self.sb_wineasio_outs)
        self.verticalLayout_22.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem25 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem25)
        self.cb_wineasio_hw = QtGui.QCheckBox(self.groupBox_7)
        self.cb_wineasio_hw.setObjectName(_fromUtf8("cb_wineasio_hw"))
        self.horizontalLayout_21.addWidget(self.cb_wineasio_hw)
        self.verticalLayout_22.addLayout(self.horizontalLayout_21)
        self.verticalLayout_17.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.page_wineasio)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem26 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem26)
        self.cb_wineasio_autostart = QtGui.QCheckBox(self.groupBox_8)
        self.cb_wineasio_autostart.setObjectName(_fromUtf8("cb_wineasio_autostart"))
        self.horizontalLayout_22.addWidget(self.cb_wineasio_autostart)
        self.verticalLayout_23.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        spacerItem27 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem27)
        self.cb_wineasio_fixed_bsize = QtGui.QCheckBox(self.groupBox_8)
        self.cb_wineasio_fixed_bsize.setObjectName(_fromUtf8("cb_wineasio_fixed_bsize"))
        self.horizontalLayout_23.addWidget(self.cb_wineasio_fixed_bsize)
        self.verticalLayout_23.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_22 = QtGui.QLabel(self.groupBox_8)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_18.addWidget(self.label_22)
        self.cb_wineasio_bsizes = QtGui.QComboBox(self.groupBox_8)
        self.cb_wineasio_bsizes.setObjectName(_fromUtf8("cb_wineasio_bsizes"))
        self.horizontalLayout_18.addWidget(self.cb_wineasio_bsizes)
        self.verticalLayout_23.addLayout(self.horizontalLayout_18)
        self.verticalLayout_17.addWidget(self.groupBox_8)
        spacerItem28 = QtGui.QSpacerItem(20, 152, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem28)
        self.sw_tweaks.addWidget(self.page_wineasio)
        self.verticalLayout_15.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab_tweaks, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        CadenceMainW.setCentralWidget(self.centralwidget)

        self.retranslateUi(CadenceMainW)
        self.tabWidget.setCurrentIndex(0)
        self.sw_tweaks.setCurrentIndex(0)
        self.tb_tweak_plugins.setCurrentIndex(0)
        QtCore.QObject.connect(self.tw_tweaks, QtCore.SIGNAL(_fromUtf8("currentCellChanged(int,int,int,int)")), self.sw_tweaks.setCurrentIndex)
        QtCore.QObject.connect(self.ch_app_image, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cb_app_image.setEnabled)
        QtCore.QObject.connect(self.ch_app_music, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cb_app_music.setEnabled)
        QtCore.QObject.connect(self.ch_app_video, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cb_app_video.setEnabled)
        QtCore.QObject.connect(self.ch_app_text, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cb_app_text.setEnabled)
        QtCore.QObject.connect(self.ch_app_browser, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cb_app_browser.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CadenceMainW)

    def retranslateUi(self, CadenceMainW):
        CadenceMainW.setWindowTitle(_translate("CadenceMainW", "Cadence", None))
        self.label_welcome.setText(_translate("CadenceMainW", "Welcome to Cadence", None))
        self.groupBox_info.setTitle(_translate("CadenceMainW", "System Information", None))
        self.label_info_os_L.setText(_translate("CadenceMainW", "Operating System:", None))
        self.label_info_os.setText(_translate("CadenceMainW", "TextLabel", None))
        self.label_info_version_L.setText(_translate("CadenceMainW", "Kernel/Version:", None))
        self.label_info_version.setText(_translate("CadenceMainW", "TextLabel", None))
        self.label_info_arch_L.setText(_translate("CadenceMainW", "Architecture:", None))
        self.label_info_arch.setText(_translate("CadenceMainW", "TextLabel", None))
        self.groupBox_status.setTitle(_translate("CadenceMainW", "System Status", None))
        self.label_cpufreq.setText(_translate("CadenceMainW", "CPU Scaling Governor:", None))
        self.groupBox_checks.setTitle(_translate("CadenceMainW", "System Checks", None))
        self.label_check_helper3.setText(_translate("CadenceMainW", "Result", None))
        self.label_check_helper1.setText(_translate("CadenceMainW", "Test Name:", None))
        self.groupBox_jack.setTitle(_translate("CadenceMainW", "JACK Status", None))
        self.label_jack_srate_L.setText(_translate("CadenceMainW", "Sample Rate:", None))
        self.label_jack_dsp_L.setText(_translate("CadenceMainW", "DSP Load:", None))
        self.label_jack_realtime.setText(_translate("CadenceMainW", "TextLabel", None))
        self.label_jack_realtime_L.setText(_translate("CadenceMainW", "Realtime:", None))
        self.label_jack_bufsize_L.setText(_translate("CadenceMainW", "Buffer Size:", None))
        self.label_jack_dsp.setText(_translate("CadenceMainW", "TextLabel", None))
        self.label_jack_xruns_L.setText(_translate("CadenceMainW", "Xruns:", None))
        self.label_jack_status.setText(_translate("CadenceMainW", "TextLabel", None))
        self.label_jack_status_L.setText(_translate("CadenceMainW", "Server Status:", None))
        self.label_jack_latency_L.setText(_translate("CadenceMainW", "Block Latency:", None))
        self.label_jack_xruns.setText(_translate("CadenceMainW", "TextLabel", None))
        self.label_jack_bfsize.setText(_translate("CadenceMainW", "TextLabel", None))
        self.label_jack_srate.setText(_translate("CadenceMainW", "TextLabel", None))
        self.label_jack_latency.setText(_translate("CadenceMainW", "TextLabel", None))
        self.b_jack_start.setText(_translate("CadenceMainW", "Start", None))
        self.b_jack_stop.setText(_translate("CadenceMainW", "Stop", None))
        self.b_jack_restart.setText(_translate("CadenceMainW", "Force Restart", None))
        self.b_jack_configure.setText(_translate("CadenceMainW", "Configure", None))
        self.b_jack_switchmaster.setText(_translate("CadenceMainW", "Switch Master", None))
        self.cb_jack_autostart.setText(_translate("CadenceMainW", "Auto-start JACK or LADISH at login", None))
        self.tb_jack_options.setText(_translate("CadenceMainW", "...", None))
        self.groupBox_bridges.setTitle(_translate("CadenceMainW", "JACK Bridges", None))
        self.label_bridge_alsa.setText(_translate("CadenceMainW", "No bridge in use", None))
        self.b_alsa_start.setText(_translate("CadenceMainW", "Start", None))
        self.b_alsa_stop.setText(_translate("CadenceMainW", "Stop", None))
        self.label.setText(_translate("CadenceMainW", "Bridge Type:", None))
        self.cb_alsa_type.setItemText(0, _translate("CadenceMainW", "(None)", None))
        self.cb_alsa_type.setItemText(1, _translate("CadenceMainW", "ALSA -> Loop -> JACK", None))
        self.cb_alsa_type.setItemText(2, _translate("CadenceMainW", "ALSA -> JACK (Plugin)", None))
        self.cb_alsa_type.setItemText(3, _translate("CadenceMainW", "ALSA -> PulseAudio -> JACK (Plugin)", None))
        self.tb_alsa_options.setText(_translate("CadenceMainW", "...", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.toolBox_alsaaudio), _translate("CadenceMainW", "ALSA Audio", None))
        self.label_bridge_a2j.setText(_translate("CadenceMainW", "ALSA MIDI State", None))
        self.b_a2j_start.setText(_translate("CadenceMainW", "Start", None))
        self.b_a2j_stop.setText(_translate("CadenceMainW", "Stop", None))
        self.b_a2j_export_hw.setText(_translate("CadenceMainW", "Export HW...", None))
        self.cb_a2j_autostart.setText(_translate("CadenceMainW", "Auto-start at login", None))
        self.tb_a2j_options.setText(_translate("CadenceMainW", "...", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.toolBox_alsamidi), _translate("CadenceMainW", "ALSA MIDI", None))
        self.label_bridge_pulse.setText(_translate("CadenceMainW", "PulseAudio state", None))
        self.b_pulse_start.setText(_translate("CadenceMainW", "Start", None))
        self.b_pulse_stop.setText(_translate("CadenceMainW", "Stop", None))
        self.cb_pulse_autostart.setText(_translate("CadenceMainW", "Auto-start at login", None))
        self.tb_pulse_options.setText(_translate("CadenceMainW", "...", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.toolBox_pulseaudio), _translate("CadenceMainW", "PulseAudio", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_system), _translate("CadenceMainW", "System", None))
        self.label_tools_apps.setText(_translate("CadenceMainW", "Applications", None))
        self.groupBox_catia.setTitle(_translate("CadenceMainW", "Catia", None))
        self.label_tools_catia.setText(_translate("CadenceMainW", "JACK Patchbay with A2J Bridge support and JACK Transport", None))
        self.groupBox_claudia.setTitle(_translate("CadenceMainW", "Claudia", None))
        self.label_tools_claudia.setText(_translate("CadenceMainW", "LADISH frontend; like Catia, but focused at session management", None))
        self.groupBox_meter.setTitle(_translate("CadenceMainW", "Meter In / Out", None))
        self.label_tools_meter.setText(_translate("CadenceMainW", "Digital peak meter, auto-connected to all system inputs or outputs", None))
        self.label_tools_tools.setText(_translate("CadenceMainW", "Tools", None))
        self.groupBox_logs.setTitle(_translate("CadenceMainW", "Logs", None))
        self.label_tools_logs.setText(_translate("CadenceMainW", "View JACK, A2J and LADISH logs", None))
        self.groupBox_render.setTitle(_translate("CadenceMainW", "Render", None))
        self.label_tools_render.setText(_translate("CadenceMainW", "Render a JACK project", None))
        self.groupBox_xycontroller.setTitle(_translate("CadenceMainW", "XY-Controller", None))
        self.label_tools_xycontroller.setText(_translate("CadenceMainW", "Virtual XY Controller with MIDI Keyboard", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tools), _translate("CadenceMainW", "Tools", None))
        self.label_tweaks.setText(_translate("CadenceMainW", "Tweaks", None))
        self.label_2.setText(_translate("CadenceMainW", "Settings have been changed", None))
        self.b_tweaks_apply_now.setText(_translate("CadenceMainW", "Apply Now", None))
        item = self.tw_tweaks.verticalHeaderItem(0)
        item.setText(_translate("CadenceMainW", "audio-plugins", None))
        item = self.tw_tweaks.verticalHeaderItem(1)
        item.setText(_translate("CadenceMainW", "default-apps", None))
        item = self.tw_tweaks.verticalHeaderItem(2)
        item.setText(_translate("CadenceMainW", "wineasio", None))
        item = self.tw_tweaks.horizontalHeaderItem(0)
        item.setText(_translate("CadenceMainW", "name", None))
        __sortingEnabled = self.tw_tweaks.isSortingEnabled()
        self.tw_tweaks.setSortingEnabled(False)
        item = self.tw_tweaks.item(0, 0)
        item.setText(_translate("CadenceMainW", "Audio Plugins PATH", None))
        item = self.tw_tweaks.item(1, 0)
        item.setText(_translate("CadenceMainW", "Default Applications", None))
        item = self.tw_tweaks.item(2, 0)
        item.setText(_translate("CadenceMainW", "WineASIO", None))
        self.tw_tweaks.setSortingEnabled(__sortingEnabled)
        self.b_tweak_plugins_remove.setText(_translate("CadenceMainW", "Remove", None))
        self.b_tweak_plugins_add.setText(_translate("CadenceMainW", "Add...", None))
        self.tb_tweak_plugins.setItemText(self.tb_tweak_plugins.indexOf(self.page_ladspa), _translate("CadenceMainW", "LADSPA", None))
        self.tb_tweak_plugins.setItemText(self.tb_tweak_plugins.indexOf(self.page_dssi), _translate("CadenceMainW", "DSSI", None))
        self.tb_tweak_plugins.setItemText(self.tb_tweak_plugins.indexOf(self.page_lv2), _translate("CadenceMainW", "LV2", None))
        self.tb_tweak_plugins.setItemText(self.tb_tweak_plugins.indexOf(self.page_vst), _translate("CadenceMainW", "VST", None))
        self.b_tweak_plugins_reset.setText(_translate("CadenceMainW", "Reset", None))
        self.b_tweak_plugins_change.setText(_translate("CadenceMainW", "Change...", None))
        self.ch_app_image.setText(_translate("CadenceMainW", "Image Viewer", None))
        self.ch_app_text.setText(_translate("CadenceMainW", "Text Editor", None))
        self.ch_app_video.setText(_translate("CadenceMainW", "Video Player", None))
        self.ch_app_music.setText(_translate("CadenceMainW", "Music Player", None))
        self.ch_app_browser.setText(_translate("CadenceMainW", "Web Browser", None))
        self.label_app_name.setText(_translate("CadenceMainW", "[App Name]", None))
        self.label_app_comment.setText(_translate("CadenceMainW", "[App Comment]", None))
        self.groupBox_7.setTitle(_translate("CadenceMainW", "Audio Ports", None))
        self.label_7.setToolTip(_translate("CadenceMainW", "Number of jack ports that wineasio will try to open.\n"
"Default is 16", None))
        self.label_7.setText(_translate("CadenceMainW", "Number of inputs:", None))
        self.sb_wineasio_ins.setToolTip(_translate("CadenceMainW", "Number of jack ports that wineasio will try to open.\n"
"Default is 16", None))
        self.label_21.setToolTip(_translate("CadenceMainW", "Number of jack ports that wineasio will try to open.\n"
"Default is 16", None))
        self.label_21.setText(_translate("CadenceMainW", "Number of outputs:", None))
        self.sb_wineasio_outs.setToolTip(_translate("CadenceMainW", "Number of jack ports that wineasio will try to open.\n"
"Default is 16", None))
        self.cb_wineasio_hw.setToolTip(_translate("CadenceMainW", "Try to connect the asio channels to the\n"
"physical I/O ports on your hardware.\n"
"Default is on", None))
        self.cb_wineasio_hw.setText(_translate("CadenceMainW", "Connect to hardware", None))
        self.groupBox_8.setTitle(_translate("CadenceMainW", "JACK Options", None))
        self.cb_wineasio_autostart.setToolTip(_translate("CadenceMainW", "Enable wineasio to launch the jack server.\n"
"Default is off", None))
        self.cb_wineasio_autostart.setText(_translate("CadenceMainW", "Autostart server", None))
        self.cb_wineasio_fixed_bsize.setToolTip(_translate("CadenceMainW", "When on, an asio app will be able to change the jack buffer size.\n"
"Default is off", None))
        self.cb_wineasio_fixed_bsize.setText(_translate("CadenceMainW", "Fixed buffersize", None))
        self.label_22.setText(_translate("CadenceMainW", "Preferred buffersize:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tweaks), _translate("CadenceMainW", "Tweaks", None))

from clickablelabel import ClickableLabel
import resources_rc
